---
repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-alfred
          - flake8-breakpoint
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-logging-format
          - flake8-return
